services:
  db:
    image: mysql:8.0
    container_name: wedding-db
    environment:
      MYSQL_ROOT_PASSWORD: "!QAZ2wsx#EDC"
      MYSQL_DATABASE: wedding
      MYSQL_USER: wedding_user
      MYSQL_PASSWORD: "!QAZ2wsx#EDC"
    ports:
      - "3336:3306"
    volumes:
      - ./data/db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wedding-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "!QAZ2wsx#EDC"
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-backend
    environment:
      PORT: 5000
      DB_HOST: db
      DB_NAME: wedding
      DB_USER: root
      DB_PASS: "!QAZ2wsx#EDC"
      DB_PORT: 3306
      DB_DIALECT: mysql
    restart: always
    depends_on:
      - db
    ports:
      - "4567:5000"

  frontend:
    image: zed378/wedding-invitation:latest
    container_name: wedding-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3001:3001
